code/dragon_hoard/config/routes.rb
DragonHoard::Application.routes.draw do
  

  devise_for :users do
    get "users/sign_out" => 'devise/sessions#destroy'
  end

  resources :accounts do 
    resources :transactions
  end
  get "home/index"
  root :to => 'home#index'

  

end

code/dragon_hoard/app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :name
  
  has_many :transactions
  
end

code/dragon_hoard/app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :amount, :cleared, :date, :date_cleared, :payee
  
  belongs_to :account
end

code/dragon_hoard/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

code/dragon_hoard/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

code/dragon_hoard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
end

code/dragon_hoard/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  
  def index
  end
end

code/dragon_hoard/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  before_filter :get_accounts
  
  def get_accounts 
    @account = Account.find(params[:account_id])
  end
  
  def index
    @transactions = @account.transactions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = @account.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = @account.transactions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = @account.transactions.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = @account.transactions.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to account_transaction_url(@account, @transaction), notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = @account.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to account_transaction_url(@account, @transaction), notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = @account.transactions.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to account_transactions_url(@account) }
      format.json { head :no_content }
    end
  end
end

code/dragon_hoard/app/helpers/accounts_helper.rb
module AccountsHelper
end

code/dragon_hoard/app/helpers/application_helper.rb
module ApplicationHelper
end

code/dragon_hoard/app/helpers/home_helper.rb
module HomeHelper
end

code/dragon_hoard/app/helpers/transactions_helper.rb
module TransactionsHelper
end

code/dragon_hoard/app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code/dragon_hoard/app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

code/dragon_hoard/app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

code/dragon_hoard/app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

code/dragon_hoard/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>| <%= link_to 'Transactions', account_transactions_path(:account_id => @account.id) %>

code/dragon_hoard/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

code/dragon_hoard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragonHoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if @current_user.nil? %>
<a href='<%= destroy_user_session_path %>' method="DELETE">sign out </a>
<% end %>

<%= yield %>

</body>
</html>

code/dragon_hoard/app/views/transactions/_form.html.erb
<%= form_for(@transaction, :url => url) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payee %><br />
    <%= f.text_field :payee %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :cleared %><br />
    <%= f.check_box :cleared %>
  </div>
  <div class="field">
    <%= f.label :date_cleared %><br />
    <%= f.date_select :date_cleared %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code/dragon_hoard/app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form', :url => account_transaction_path(@account, @transaction) %>

<%= link_to 'Show', account_transaction_path(@account, @transaction) %> |
<%= link_to 'Back', account_transactions_path(@account) %>

code/dragon_hoard/app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Payee</th>
    <th>Date</th>
    <th>Amount</th>
    <th>Cleared</th>
    <th>Date cleared</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.payee %></td>
    <td><%= transaction.date %></td>
    <td><%= transaction.amount %></td>
    <td><%= transaction.cleared %></td>
    <td><%= transaction.date_cleared %></td>
    <td><%= link_to 'Show', account_transaction_path(transaction.account_id, transaction.id) %></td>
    <td><%= link_to 'Edit', edit_account_transaction_path(transaction.account_id, transaction.id) %></td>
    <td><%= link_to 'Destroy', account_transaction_path(transaction.account_id, transaction.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_account_transaction_path(@account.id) %>

code/dragon_hoard/app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form', :url => account_transactions_path(@account.id) %>

<%= link_to 'Back', account_transactions_path(@account) %>

code/dragon_hoard/app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Payee:</b>
  <%= @transaction.payee %>
</p>

<p>
  <b>Date:</b>
  <%= @transaction.date %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>

<p>
  <b>Cleared:</b>
  <%= @transaction.cleared %>
</p>

<p>
  <b>Date cleared:</b>
  <%= @transaction.date_cleared %>
</p>


<%= link_to 'Edit', edit_account_transaction_path(@transaction.account_id, @transaction.id) %> |
<%= link_to 'Back', account_transactions_path(@account) %>